### ISSUE TITLE
Conditionaly add JSON_PRETTY_PRINT to JSON output

### ISSUE THREAD

**Issue by toolstack** [swissspidy/glotpress-json#2]
The current output from the plugin is not particularly human friendly, PHP's `json_encode()` added the `JSON_PRETTY_PRINT` option in PHP 5.4.

Conditionally adding the option for PHP 5.4 or above would make the output much nicer for most users.

```
        $options = 0;

        if ( defined( 'JSON_PRETTY_PRINT' ) ) {
            $options = JSON_PRETTY_PRINT;
        }

        $result = wp_json_encode( $result, $options );
```

**Comment by ocean90** [comment]
Does it really need to be readable by users? How does it affect the file size?

**Comment by toolstack** [comment]
I did a quick compare with an export of 610 strings:
- ugly = 129k
- pretty = 155k

Though honestly it's JavaScript so you're going to probably end up running it through a minification stage before you send it out with your app.

It would makes sense to also add a header comment to identify the generator and other info.

**Comment by swissspidy** [comment]
What about adding a `gp_json_export_pretty_print` filter? Pretty print could be off by default.

Oh, and since `JSON_PRETTY_PRINT` is always defined in WordPress, we could simply use `wp_json_encode( $result, JSON_PRETTY_PRINT )`.

> It would makes sense to also add a header comment to identify the generator and other info.

JSON doesn't allow for comments.

**Comment by toolstack** [comment]
> What about adding a gp_json_export_pretty_print filter? Pretty print could be off by default.

I don't think a filter is a good way to control that kind of output, either it should be pretty or it should be ugly, let's choose one and use it.

> Oh, and since JSON_PRETTY_PRINT is always defined in WordPress, we could simply use wp_json_encode( $result, JSON_PRETTY_PRINT ).

So what happens if we pass JSON_PRETTY_PRINT to PHP 5.3?  Does it throw an error or gracefully ignore it?

> JSON doesn't allow for comments.

Well that sucks.

**Comment by swissspidy** [comment]
> So what happens if we pass JSON_PRETTY_PRINT to PHP 5.3? Does it throw an error or gracefully ignore it?

It's simply ignored.

**Comment by toolstack** [comment]
> > JSON doesn't allow for comments.
> 
> Well that sucks.

I poked around the net some and the general consensus seems to be to use `_comment` or `__comment` to store any comments in.

That could cause a collision if someone translated a string of the same name, but that seems highly unlikely and we could do a check for it during the export or just make it a bit more unique like `__glotpress_comment` or `__glotpress_export_data` and define the structure inside as an array with the values we want to store.
