### ISSUE TITLE
Meta data is missing?

### ISSUE THREAD

**Issue by ocean90** [swissspidy/glotpress-json#4]
@toolstack mentioned this in https://github.com/swissspidy/glotpress-json/issues/2#issuecomment-249671093. Instead of a regular comment those could be part of the JSON object.

Example: https://github.com/Automattic/jetpack/blob/master/languages/json/jetpack-af.json

I'm particularly interested in the `po-revision-date` field (can be another name of course) because that's what WordPress needs for the update checks. See [`wp_get_installed_translations()`](https://github.com/WordPress/WordPress/blob/3f51e08ac6157b7b3be5eebcc44b4a16fc86674d/wp-includes/l10n.php#L990) and [`wp_get_pomo_file_data()`](https://github.com/WordPress/WordPress/blob/3f51e08ac6157b7b3be5eebcc44b4a16fc86674d/wp-includes/l10n.php#L995-L1015).

So far only [the PO format](https://github.com/GlotPress/GlotPress-WP/blob/59091bee9d0a0258de2d40af37b3be02e26fe686/gp-includes/formats/format_pomo.php#L16-L21) adds meta data to the file so I'm not sure if the JSON format should support this by default.

**Comment by swissspidy** [comment]
Update checks is a good point.

Note: the Jetpack example is the default po2json output, not Jed 1 or Jed 1.x.

So maybe we'd want to export that, or a mix of those methods.

**Comment by swissspidy** [comment]
I was wondering why Jetpack uses such output. Turns out, the i18n-calypso library uses Jed 1.0.2, i.e. the older format.

Since we need files with meta data anyway, perhaps we should have a (third) format that is basically a wrapper around the Jed 1.x output. It would contain all the data we need and when loading it, only the relevant part would need to be passed to Jed.

**Comment by ocean90** [comment]
> Since we need files with meta data anyway, perhaps we should have a (third) format that is basically a wrapper around the Jed 1.x output

I tend to agree. Since this is special to wordpress.org it doesn't need to be handled by the plugin (or GlotPress).

I need a custom format anyway because I have to adjust the `domain` value. Or should the format use the project slug as the default value? Related: https://github.com/GlotPress/GlotPress-WP/commit/30e7179e4e9989282d8f8666b2fc5dc36ef3f2b0

**Comment by swissspidy** [comment]
I don't know why adjusting the `domain` is needed, but whatever works for GlotPress and dotorg. Shall I create a PR on the GlotPress repo with the existing code and only keep a new custom format in this plugin?

**Comment by ocean90** [comment]
Yep, a PR would be great. The custom format will probably be integrated into of the GP plugins we already have but feel free to start with this plugin.

**Comment by swissspidy** [comment]
So, an example Jed JSON file used in GlotPress/GlotPress-WP#567 looks like this (ignore the bad plural form):

``` json
{
  "domain":      "messages",
  "locale_data": {
    "messages": {
      "":                                                             {
        "domain":       "messages",
        "plural-forms": "n != 1",
        "lang":         "de-ch"
      },
      "Foo": []
    }
  }
}
```

To make checking for and retrieving meta data as simple as possible, I'd suggest adding it to the top level, like this:

``` json
{
  "translation-revision-date": "+0000",
  "x-generator": "GlotPress/2.3.0-alpha",
  "domain": "messages",
  "locale_data": {
    "messages": {
      "": {
        "domain":       "messages",
        "plural-forms": "n != 1",
        "lang":         "de-ch"
      },
      "Foo": []
    }
  }
}
```

The only thing important to Jed is the `domain` key and everything inside `locale_data[ domain ]`. Anything else would safely be ignored, so we can add custom keys in the root.

I don't think these two new fields should be prefixed with an underscore or something.

**Comment by ocean90** [comment]
@swissspidy `x-` is actually a prefix. :) It's usually used to define unstandardized elements. (List of headers for PO files: https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html)

Since `generator` and `translation-revision-date` are not part of the Jed format we could prefix them with `x-`. But I don't think that it's really necessary.

**Comment by swissspidy** [comment]
`generator` and `translation-revision-data` it is then. Will add this to the PR.
